apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: airflow
    meta.helm.sh/release-namespace: airflow
  creationTimestamp: "2025-06-22T03:16:33Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.16.0
    component: webserver
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-webserver-lb
  namespace: airflow
  
spec:
  #clusterIP: 10.100.157.0
  #clusterIPs:
  #- 10.100.157.0
  #internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: airflow-ui
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: webserver
    release: airflow
    tier: airflow
  sessionAffinity: None
  type: LoadBalancer
